- stat: path={{ fonts_dir }}/{{ font_filename }}
  register: st
  changed_when: false

- get_url: url={{ font_url }} dest={{ fonts_dir }}/{{ font_filename }}
  when: not st.stat.exists

- git:
    repo: git@github.com:bentsolheim/Monokai_Fish_OSX.git
    dest: "{{general.local_home}}/Downloads/Monokai_Fish_OSX"
    update: yes

- name: Get current Terminal profile.
  shell: defaults read com.apple.Terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: open "{{general.local_home}}/Downloads/Monokai_Fish_OSX/Monokai_Inconsolata.terminal"
  changed_when: false
  when: "'Monokai_Inconsolata' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.Terminal 'Default Window Settings' -string 'Monokai_Inconsolata'
    - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Monokai_Inconsolata'
    - "fish {{general.local_home}}/Downloads/Monokai_Fish_OSX/set_colors.fish"
  changed_when: false
  when: "'Monokai_Inconsolata' not in terminal_theme.stdout"